/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaBanco.java
 *
 * Created on 06/04/2012, 00:01:54
 */
package com.java.geraDTO.form;

/**
 *
 * @author WILL
 */
public class TelaBanco extends javax.swing.JFrame {

    /** Creates new form TelaBanco */
    public TelaBanco() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btPegarTabelas = new javax.swing.JButton();
        btPegarCampos = new javax.swing.JButton();
        cbTabelas = new javax.swing.JComboBox();
        cbCampos = new javax.swing.JComboBox();
        btGeraDTO = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbOk = new javax.swing.JLabel();
        tfPacote = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfConexao = new javax.swing.JTextField();
        cbSSGBD = new javax.swing.JComboBox();
        tfHost = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        tfSenha = new javax.swing.JPasswordField();
        lbJava = new javax.swing.JLabel();
        lbJavaBall = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerador de DTO E DAO 3.0");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btPegarTabelas.setText("Pegar Tabelas");
        jPanel1.add(btPegarTabelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 107, 109, -1));

        btPegarCampos.setText("Pegar Colunas");
        jPanel1.add(btPegarCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 136, 109, -1));

        jPanel1.add(cbTabelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 192, -1));

        jPanel1.add(cbCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 190, -1));

        btGeraDTO.setText("GERA DTO/DAO");
        jPanel1.add(btGeraDTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pacote de de implat. ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 171, 109, -1));

        lbOk.setForeground(new java.awt.Color(255, 255, 255));
        lbOk.setText("STATUS...");
        jPanel1.add(lbOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        tfPacote.setText("com.bia.seller.control.utilitarios");
        tfPacote.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(tfPacote, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 199, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Classe Conexao        ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 197, 109, -1));

        tfConexao.setText("conexao");
        tfConexao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(tfConexao, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 200, 20));

        cbSSGBD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "com.mysql.jdbc.Driver", "oracle.jdbc.driver.OracleDriver", "net.sourceforge.jtds.jdbc.Driver", "sun.jdbc.odbc.JdbcOdbcDriver", "com.sybase.jdbc4.jdbc.SybDriver", "sun.jdbc.odbc.JdbcOdbcDriver", "com.microsoft.sqlserver.jdbc.SQLServerDriver" }));
        cbSSGBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSSGBDActionPerformed(evt);
            }
        });
        jPanel1.add(cbSSGBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 300, -1));

        tfHost.setText("jdbc:mysql://instance9411.db.xeround.com.:5879/controlon");
        tfHost.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(tfHost, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 240, 20));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SGDB ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 22, 109, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Host do Data Base      ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 54, 109, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Usuario");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 82, 50, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Senha");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, 20));

        tfUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(tfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 61, 20));

        tfSenha.setText("will03");
        tfSenha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(tfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 80, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 360, 270));

        lbJava.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/geraDTO/image/java12.jpg"))); // NOI18N
        lbJava.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(lbJava, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 320));

        lbJavaBall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/geraDTO/image/javaBall.png"))); // NOI18N
        lbJavaBall.setEnabled(false);
        getContentPane().add(lbJavaBall, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));
        lbJavaBall.getAccessibleContext().setAccessibleName("lbJavaBall");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbSSGBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSSGBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSSGBDActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btGeraDTO;
    public javax.swing.JButton btPegarCampos;
    public javax.swing.JButton btPegarTabelas;
    public javax.swing.JComboBox cbCampos;
    public javax.swing.JComboBox cbSSGBD;
    public javax.swing.JComboBox cbTabelas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lbJava;
    public javax.swing.JLabel lbJavaBall;
    public javax.swing.JLabel lbOk;
    public javax.swing.JTextField tfConexao;
    public javax.swing.JTextField tfHost;
    public javax.swing.JTextField tfPacote;
    public javax.swing.JPasswordField tfSenha;
    public javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
